server {
    listen 80;
    server_name thirunavukkarasuthangaraj.fun;

    # Serve Angular static files
    location / {
        root /var/www/html/angular-app;
        try_files $uri $uri/ /index.html;
        index index.html;
    }

    # Proxy API requests to your Spring Boot app
    location /api {
        proxy_pass http://localhost:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}