server {
    listen 443 ssl;
    server_name thirunavukkarasuthangaraj.fun;

    ssl_certificate     /etc/letsencrypt/live/thirunavukkarasuthangaraj.fun/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/thirunavukkarasuthangaraj.fun/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name thirunavukkarasuthangaraj.fun;
    return 301 https://$host$request_uri;
}
