spring.datasource.url=jdbc:postgresql://database-1.cy34wwy06ef1.us-east-1.rds.amazonaws.com:5432/database-1
spring.datasource.username=postgres
spring.datasource.password=Thiruna123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Kafka Broker
spring.cloud.stream.kafka.binder.brokers=localhost:9092

# Topics
spring.cloud.stream.bindings.employeeAddOutput.destination=topic/employee-add
spring.cloud.stream.bindings.employeeUpdateOutput.destination=topic/employee-update
spring.cloud.stream.bindings.employeeAddInput.destination=topic/employee-add
spring.cloud.stream.bindings.employeeUpdateInput.destination=topic/employee-update

# Content Type
spring.cloud.stream.bindings.employeeAddOutput.content-type=application/json
spring.cloud.stream.bindings.employeeUpdateOutput.content-type=application/json
spring.cloud.stream.bindings.employeeAddInput.content-type=application/json
spring.cloud.stream.bindings.employeeUpdateInput.content-type=application/json