name: Deploy Spring Boot to AWS EC2

on:
  push:
    paths:
      - 'springboot-backend/**'  # Runs only when backend files change

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot App
        run: |
          cd springboot-backend
          mvn clean install -DskipTests

      - name: Debug - Check JAR File
        run: |
          ls -l springboot-backend/target/

      - name: Save EC2 SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem  # Secure SSH key

      - name: Transfer JAR to EC2
        run: |
          echo "Copying JAR to EC2..."
          scp -o StrictHostKeyChecking=no -i ec2_key.pem springboot-backend/target/springboot-backend-0.0.1-SNAPSHOT.jar ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/app.jar

      - name: Restart Application on EC2
        run: | 
          echo "Restarting application..."
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} <<EOF
            sudo kill -9 $(lsof -t -i:8080) || true
            nohup java -jar /home/ubuntu/app.jar > /home/ubuntu/app.log 2>&1 &
          EOF
