name: Deploy Spring Boot to AWS EC2

on:
  push:
    paths:
      - 'springboot-backend/**'  # Runs only when backend files change

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot App
        run: |
          cd springboot-backend
          mvn clean install -DskipTests

      - name: Transfer JAR to EC2
        run: |
          scp -i ${{ secrets.EC2_SSH_KEY }} springboot-backend/target/*.jar ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/app.jar

      - name: Restart Application on EC2
        run: |
          ssh -i ${{ secrets.EC2_SSH_KEY }} ubuntu@${{ secrets.EC2_PUBLIC_IP }} <<EOF
            sudo kill -9 $(lsof -t -i:8080) || true
            nohup java -jar /home/ubuntu/app.jar > /home/ubuntu/app.log 2>&1 &
          EOF
