name: Deploy Backend, Frontend, Postgres via Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH to EC2 and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          cd /home/ec2-user/curd
          git pull origin main

          # Build backend jar again
          cd springboot-backend
          ./mvnw clean package -DskipTests || mvn clean package -DskipTests

          # Copy the generated jar
          cp target/*.jar ../springboot-backend/springboot-backend-0.0.1.jar

          cd ..

          # Restart docker-compose
          docker-compose down
          docker-compose build
          docker-compose up -d
