name: Deploy Backend, Frontend, Postgres via Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          # Go inside project folder
          cd /home/ec2-user/curd

          # 🛜 Create swap memory if not already created
          if [ ! -f /swapfile ]; then
            echo "Creating SWAP memory..."
            sudo fallocate -l 2G /swapfile
            sudo chmod 600 /swapfile
            sudo mkswap /swapfile
            sudo swapon /swapfile
          fi

          # 🛜 Display swap info
          sudo swapon --show

          # 📦 Pull latest code
          git pull origin main

          # 📦 Build backend
          cd springboot-backend
          ./mvnw clean package -DskipTests || mvn clean package -DskipTests

          # 🛠️ Build and Deploy containers
          cd ..
          docker-compose down
          docker-compose build
          docker-compose up -d
