jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
        working-directory: angular-frontend

      - name: Build Angular app
        run: npm run build --prod
        working-directory: angular-frontend

      - name: Deploy to S3
        run: |
          aws s3 sync angular-frontend/dist/angular-frontend s3://ui-thiru --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1  # Change to your correct AWS region
